export const routeMap = {
	//  医院管理
	'hospital': true,
	//  新增医院
	'addHospital': true,
	//	编辑医院
	'editHospital': true,
	//  科室管理
	'department': true,
	//  新增科室
	'addDepartment': true,
	//  编辑科室
	'editDepartment': true,
	//  疾病管理
	'disease': true,
	//  新增疾病
	'addDisease': true,
	//  编辑疾病
	'editDisease': true,
	//  医生管理
	'doctor': true,
	//  新增医生
	'addDoctor': true,
	//  编辑医生
	'editDoctor': true,
	//  用户管理
	'user': true,
	//	⚠️原型图没有
	//  新增用户
	// 'newUser': true,
	//  编辑用户
	'editUser': true,
	//  家庭组
	'familyGroup': true,
	//	⚠️原型图没有
	//  新增家庭组
	// 'newFamilyGroup': true,
	//	⚠️原型图没有
	//  公司信息
	//	'companyInfo': true,
	//  商品管理
	'commodity': true,
	//  添加商品
	'addCommodity': true,
	//  编辑商品
	'editCommodity': true,
	//  统计管理
	'statistical': true,
	//  方案管理
	'scheme': true,
	//  宣教管理
	'mission': true,
	//  系统设置
	'system': true,
	//  修改密码
	'changePassword': true,
	//  角色管理
	'role': true,
	//  账号管理
	'account': true,
};